### ISSUE TITLE
缺少com.lufficc.ishuhui.Config类

### ISSUE THREAD

**Issue by wanglou-xsj** [lufficc/iShuiHui#1]
Error:(13, 27) 错误: 找不到符号
符号:   类 Config
位置: 程序包 com.lufficc.ishuhui

**Comment by lufficc** [comment]
这个Config类里面只有两个静态常量，一个是Api_key，还有一个是软件的id,你可以去fir.im注册账号免费申请哦，这是用来检查更新用的，所以不能上传上来让大家测试啦
